package com.unipath.repository;

import com.unipath.model.Report;
import javafx.application.Platform;
import javafx.stage.FileChooser;
import javafx.stage.Window;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Map;

public class ReportRepository {

    public void saveReport(Report report, int secretaryId) throws Exception {

        Platform.runLater(() -> {
            FileChooser fileChooser = new FileChooser();
            fileChooser.setTitle("Αποθήκευση Αναφοράς στον Υπολογιστή");

            if ("PDF".equalsIgnoreCase(report.getFormat())) {
                fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("PDF Files (*.pdf)", "*.pdf"));
                fileChooser.setInitialFileName("Statistical_Report_" + secretaryId + ".pdf");
            } else {
                fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("Word Files (*.docx)", "*.docx"));
                fileChooser.setInitialFileName("Statistical_Report_" + secretaryId + ".docx");
            }

            Window ownerWindow = Window.getWindows().stream()
                    .filter(Window::isShowing)
                    .findFirst()
                    .orElse(null);

            File file = fileChooser.showSaveDialog(ownerWindow);

            if (file != null) {
                try {
                    if ("PDF".equalsIgnoreCase(report.getFormat())) {
                        writePdf(report, file);
                    } else {
                        writeDocx(report, file);
                    }
                    System.out.println("Η αναφορά αποθηκεύτηκε επιτυχώς τοπικά!");
                } catch (IOException e) {
                    System.err.println("Error saving file: " + e.getMessage());
                }
            }
        });
    }

    private void writePdf(Report report, File file) throws IOException {
        try (PDDocument document = new PDDocument()) {
            PDPage page = new PDPage();
            document.addPage(page);

            try (PDPageContentStream contentStream = new PDPageContentStream(document, page)) {
                contentStream.beginText();
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 16);
                contentStream.newLineAtOffset(50, 750);
                contentStream.showText("UniPath - Statistical Analysis Report");

                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
                contentStream.newLineAtOffset(0, -40);
                contentStream.showText("Generated by Secretary ID: " + report.getGeneratedBy());

                contentStream.newLineAtOffset(0, -20);
                String filterText = report.getAppliedFilters() != null ? report.getAppliedFilters().toString() : "No Filters Applied";
                contentStream.showText("Filters: " + filterText.replaceAll("[{}']", ""));

                // Διάβασμα των πραγματικών στατιστικών από τον Controller
                contentStream.newLineAtOffset(0, -40);
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 14);
                contentStream.showText("Calculated Metrics:");
                contentStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);

                if (report.getStatistics() != null) {
                    contentStream.newLineAtOffset(0, -20);
                    contentStream.showText("Total Study Plans: " + report.getStatistics().get("totalPlans"));
                    contentStream.newLineAtOffset(0, -20);
                    contentStream.showText("Average ECTS: " + report.getStatistics().get("averageECTS"));
                }
                contentStream.endText();
            }
            document.save(file);
        }
    }

    private void writeDocx(Report report, File file) throws IOException {
        try (XWPFDocument document = new XWPFDocument();
             FileOutputStream out = new FileOutputStream(file)) {

            XWPFParagraph title = document.createParagraph();
            XWPFRun titleRun = title.createRun();
            titleRun.setText("UniPath - Official Statistical Report");
            titleRun.setBold(true);
            titleRun.setFontSize(18);

            XWPFParagraph body = document.createParagraph();
            XWPFRun bodyRun = body.createRun();
            bodyRun.addBreak();
            bodyRun.setText("Generated by Secretary ID: " + report.getGeneratedBy());
            bodyRun.addBreak();
            bodyRun.setText("Filters Applied: " + (report.getAppliedFilters() != null ? report.getAppliedFilters().toString() : "None"));
            bodyRun.addBreak();
            bodyRun.addBreak();

            if (report.getStatistics() != null) {
                bodyRun.setText("RESULTS:");
                bodyRun.addBreak();
                bodyRun.setText("• Total System Plans: " + report.getStatistics().get("totalPlans"));
                bodyRun.addBreak();
                bodyRun.setText("• Average ECTS Value: " + report.getStatistics().get("averageECTS"));
                bodyRun.addBreak();
                bodyRun.setText("• Plans Per Direction: " + report.getStatistics().get("plansPerDirection"));
                bodyRun.addBreak();
                bodyRun.setText("• Plans Per Academic Year: " + report.getStatistics().get("plansPerYear"));
            }

            document.write(out);
        }
    }
}